"""Initial migration

Revision ID: 030311e1c686
Revises: 
Create Date: 2025-03-07 11:00:08.701398

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '030311e1c686'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs_vendas')
    with op.batch_alter_table('Cliente', schema=None) as batch_op:
        batch_op.drop_index('idx_nome_cliente')

    with op.batch_alter_table('GeneroMusical', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['Nome'])

    with op.batch_alter_table('ItensVenda', schema=None) as batch_op:
        batch_op.alter_column('IDVenda',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('IDVinil',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('Usuario', schema=None) as batch_op:
        batch_op.alter_column('Tipo',
               existing_type=mysql.ENUM('admin', 'comum'),
               type_=sa.String(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'comum'"))

    with op.batch_alter_table('Venda', schema=None) as batch_op:
        batch_op.drop_index('idx_data_venda')

    with op.batch_alter_table('Vinil', schema=None) as batch_op:
        batch_op.alter_column('Titulo',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('Artista',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('AnoLancamento',
               existing_type=mysql.YEAR(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('Preco',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('IDGeneroMusical',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_index('idx_titulo_vinil')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Vinil', schema=None) as batch_op:
        batch_op.create_index('idx_titulo_vinil', ['Titulo'], unique=False)
        batch_op.alter_column('IDGeneroMusical',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('Preco',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('AnoLancamento',
               existing_type=sa.Integer(),
               type_=mysql.YEAR(),
               existing_nullable=True)
        batch_op.alter_column('Artista',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('Titulo',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('Venda', schema=None) as batch_op:
        batch_op.create_index('idx_data_venda', ['DataVenda'], unique=False)

    with op.batch_alter_table('Usuario', schema=None) as batch_op:
        batch_op.alter_column('Tipo',
               existing_type=sa.String(length=10),
               type_=mysql.ENUM('admin', 'comum'),
               existing_nullable=False,
               existing_server_default=sa.text("'comum'"))

    with op.batch_alter_table('ItensVenda', schema=None) as batch_op:
        batch_op.alter_column('IDVinil',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('IDVenda',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('GeneroMusical', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('Cliente', schema=None) as batch_op:
        batch_op.create_index('idx_nome_cliente', ['Nome'], unique=False)

    op.create_table('logs_vendas',
    sa.Column('id_log', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('operacao', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('id_venda', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_cliente', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('usuario', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('data_hora', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id_log'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
